### ISSUE TITLE
connection reset error is coming in browser and root user also cannot connect with mongo db

### ISSUE THREAD

**Issue by maaixprt** [igauravsehrawat/payroll-system#1]
connection reset error is coming in browser and root user also cannot connect with mongo db

Check pictures contains up and running on ports but application is not working. connection reset error is coming in browser
https://ibb.co/GRF8Ltt
https://ibb.co/ctN1r0M

**Comment by igauravsehrawat** [comment]
Hi @maaixprt,
Apologies for late reply.
Can you run `docker-compose -f docker-compose.dev.yml up` again?
You should be getting response on `http://localhost:4242`

<img width="659" alt="Screen Shot 2019-12-09 at 13 42 01" src="https://user-images.githubusercontent.com/3696327/70436541-d5523e00-1a89-11ea-9bd0-bc361a7aa4d1.png">


Also, this is just the backend.
To integrate it to frontend, you should use this repository https://github.com/igauravsehrawat/payroll-frontend too.

Thanks.

Let me know if this fixes it.

**Comment by maaixprt** [comment]
thanks. Now, It is working.
